# ==================================================================
# module list
# ------------------------------------------------------------------
# python        3.7    (apt)
# pytorch       1.4    (pip)
# ==================================================================
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04


COPY members.txt ./
RUN cat members.txt >> /etc/passwd

# ==================================================================
# tools
# ------------------------------------------------------------------
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
RUN apt-get update

RUN apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        wget \
        git \
        curl \
        vim \
	nano \
        libx11-dev \
        fish \
        libsparsehash-dev \
        software-properties-common \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libboost-all-dev \ 
        libreadline-gplv2-dev \
        libncursesw5-dev \
        libssl-dev \
        libsqlite3-dev \
        tk-dev \
        libgdbm-dev \
        libc6-dev \
        libbz2-dev \
        libffi-dev \
        zlib1g-dev

# ==================================================================
# python
# ------------------------------------------------------------------

RUN cd /opt && wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz && tar xzf Python-3.6.9.tgz
RUN cd /opt/Python-3.6.9 && ./configure --enable-optimizations && make altinstall
RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.6 1 && update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.6 1

# ==================================================================
# PIP
# ==================================================================

RUN curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py && python get-pip.py


# ==================================================================
# Pytorch 0.4.1 and torchvision 0.2.2
# ==================================================================

RUN pip install https://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
RUN pip install torchvision==0.2.2

# ==================================================================
# Package
# ==================================================================

RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install -r requirements.txt

WORKDIR /home


