#!/bin/bash

source config

if $REMOVE_ON_END;
then
    REMOVE_ON_END="--rm"
else
    REMOVE_ON_END=""
fi

docker run -idt \
   $REMOVE_ON_END \
    --gpus $GPUS \
    -v $PROJECT_REPO_DIR:$WORKDIR \
    --name $CONTAINER_NAME \
    $IMAGE_NAME:$IMAGE_TAG